Syslog                  yes
UMask                   007
Mode                    sv
Canonicalization        relaxed/simple
OversignHeaders         From
UserID                  opendkim
PidFile                 /run/opendkim/opendkim.pid
Domain                  kaibuilds.com
Selector                paperboy
KeyFile                 /etc/opendkim/keys/kaibuilds.com/paperboy.private
Socket                  inet:8891@localhost
